name: docker build

on:
- workflow_dispatch

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: sonalivarshney/sampleapp

  steps:
    - name: checkout
      uses: actions/checkout@v5.0.0
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker tag myapp:latest ${DOCKER_IMAGE}:latest
        docker push ${DOCKER_IMAGE}:latest

    - name: Setup kubectl
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: latest # Version of kubectl.default is latest

    - name: Setup minikube
      run: |
        minikube start # since it is on gitub hosted runner, minikube is pre installed.If running on self hosted runner, then need to install minkube using actions. 
        kubectl config use-context minikube #to ensure that subsequent kubectl commands interact with the Minikube cluster.

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        







        




        
      
        # minikube start # since it is on gitub hosted runner, minikube is pre installed.If running on self hosted runner, then need to install minkube using actions. 
        # kubectl config use-context minikube #to ensure that subsequent kubectl commands interact with the Minikube cluster.
                 
        # echo "Waiting for Minikube control plane pods to become ready..."
        # kubectl wait --for=condition=ready pod -l component=kube-apiserver -n kube-system --timeout=300s
          
        # echo "Minikube control plane is ready. Proceeding with deployment."
            
        # kubectl apply -f deployment.yaml
        # kubectl apply -f service.yaml
        
        # # Wait for your specific deployment to be rolled out and available
        # echo "Waiting for springboot-deployment to be ready..."
        # kubectl rollout status deployment/springboot-deployment --timeout=300s
        
        # kubectl get pods --all-namespaces
        # kubectl get svc
     
        # #Get service URL and curl it
        # curl $(minikube service my-service --url)
          




      




  
   

   
  
       
  
   
      
      
      
       
       
      
   
        
          
       
       
       
        
      
